### ISSUE TITLE
Field error in 0.10

### ISSUE THREAD

**Issue by bogdansoare** [jaredpalmer/formik#230]
I get the following errors after upgrading to version 0.10
```
index.js:2177 Warning: You should not use <Field component> and <Field children> in the same <Field> component; <Field component> will be ignored
```

```
formik.es6.js:2809 Uncaught TypeError: children is not a function
    at Field../node_modules/formik/dist/formik.es6.js.Field.render (formik.es6.js:2809)
```

**Comment by jaredpalmer** [comment]
Can you show me the exact code that caused the issue?

**Comment by jaredpalmer** [comment]
With `<Field>`, children has to be a function:

## Bad
```
<Field name="email">
  <div>hello</div>
</Field>
```

## Good
```
<Field name="email">
   {({field, form}) => <div>hello</div>}
</Field>
```

**Comment by bogdansoare** [comment]
Understood. What was the reason for this change? 

This a breaking change, in the release notes it's stated that there are no breaking changes.

**Comment by bogdansoare** [comment]
This is the code that I've had
```jsx
<Field
  component={FormikSelectField}
  name="availability"
  floatingLabelText="Availability"
  fullWidth
>
  {Object.keys(USER_AVAILABILITY_LABELS).map(availability => (
    <MenuItem
      key={availability}
      value={availability}
      primaryText={USER_AVAILABILITY_LABELS[availability]}
    />
  ))}
</Field>
```

```jsx
// FormikSelectField.js
import React from 'react';
import SelectField from 'material-ui/SelectField';

const FormikSelectField = ({
  field: { name, value },
  form: { touched, errors, setFieldValue, setFieldTouched },
  onChange,
  ...otherProps
}) => {
  const handleChange = (event, key, data) => {
    setFieldTouched(name, true);
    setFieldValue(name, data);

    if (onChange) {
      onChange(event, key, data);
    }
  };

  return (
    <SelectField
      errorText={touched[name] && errors[name]}
      value={value}
      onChange={handleChange}
      {...otherProps}
    />
  );
};

export default FormikSelectField;
```

How should I write it to be compatible with the new api ? because the docs really don't help

**Comment by meriadec** [comment]
Same problem here. Here is what happen when trying the select example from the docs: https://codesandbox.io/s/mzzj8618m9

```
TypeError: children is not a function
    at Field.render (https://mzzj8618m9.codesandbox.io/node_modules/formik/dist/formik.js:2812:19)
    at finishClassComponent (https://mzzj8618m9.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:10249:31)
    at updateClassComponent (https://mzzj8618m9.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:10226:12)
```

Putting `option`s as children does'nt seems to solve the problem: https://codesandbox.io/s/40z57r1n9x
No more select.

@jaredpalmer  What's your recommendation for select fields, with the new way of rendering children?

Worked well with 0.9.4, so 0.10.0 is breaking, yep.

**Comment by dccarmo** [comment]
It seems to me this issue should be reopened since it's still happening and the documentation appears to be outdated. I'll second @meriadec requesting a recommendation for best practices regarding select fields @jaredpalmer. The solution is to use `render`?

**Comment by jaredpalmer** [comment]
This was an issue in a few early versions of 0.10.x but ultimately fixed in later releases. @dccarmo there are some patches worth pushing to ppl on 0.10.x worth adding. I should probably make a link in docs.

**Comment by dccarmo** [comment]
Got it. 

I tried doing this (on TypeScript):

```
<Field
  name="Select"
  component="select"
>
  <option key="key" value="value">Option</option>
</Field>
```

And got this error

```
Types of property 'children' are incompatible.
        Type 'Element' is not assignable to type '((props: FieldProps<any>) => ReactNode) | (string & undefined) | (string & ((props: FieldProps<an...'.
          Type 'Element' is not assignable to type 'ReactPortal & ((props: FieldProps<any>) => ReactNode)'.
            Type 'Element' is not assignable to type 'ReactPortal'.
              Property 'children' is missing in type 'Element'.
```

So I assumed it was still an existing issue. 

I'll wait for the docs update to try again. Thanks!

**Comment by jaredpalmer** [comment]
what version are  you on?

**Comment by dccarmo** [comment]
0.11.7

**Comment by rylnd** [comment]
@jaredpalmer do you have a prescription for this issue? I have a similar issue with a similar setup:

```jsx
<Field
  name="Select"
  component="select"
>
  {options.map(option => (
    <option key={option.value} value={option.value}>
      {option.label}
    </option>
    ))
  }
</Field>
```

results in
```
Types of property 'children' are incompatible.
        Type 'Element[]' is not assignable to type '((props: FieldProps<any>) => ReactNode) | (string & ((props: FieldProps<any>) => ReactNode)) | (n...'.
          Type 'Element[]' is not assignable to type '(string | number | boolean | any[] | ReactElement<any>)[] & ((props: FieldProps<any>) => ReactNode)'.
            Type 'Element[]' is not assignable to type '(props: FieldProps<any>) => ReactNode'.
              Type 'Element[]' provides no match for the signature '(props: FieldProps<any>): ReactNode'.
```

on formik 0.11.10.

**Comment by jaredpalmer** [comment]
try 11.11
