### ISSUE TITLE
Unable to import Form in formik@2.0.1-rc.7

### ISSUE THREAD

**Issue by emahnovets** [jaredpalmer/formik#1631]
### Current Behavior

Got an error when trying to import `Form` component from `fomik` package. Like this:
```
import { Formik, Form } from 'formik';
```
```
semantic error TS2305 Module '"../node_modules/formik/dist"' has no exported member 'Form'.
```

### Expected behavior

In previous version We have an ability to import `Form` from `formik` package

### Additional context

For some reason in generated types we have `export default Form`;
<img width="510" alt="Screen Shot 2019-06-23 at 1 11 54 PM" src="https://user-images.githubusercontent.com/13458022/59974777-a23df000-95b8-11e9-99de-93037538f919.png">

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.1-rc.7 |
| React            | 16.8.6 |
| TypeScript       | 3.5.1 |
| Operating System | macOS 10.14.5 |

**Comment by nareshbhatia** [comment]
I am seeing the exact same behavior formik@2.0.1-rc.7

**Comment by aleksanderd** [comment]
+1

**Comment by targos** [comment]
This is because of https://github.com/microsoft/TypeScript/issues/31676

The solution for now is to downgrade typescript to 3.4.x.

**Comment by strothj** [comment]
I was able to augment the declaration for now:
`formik.d.ts`:
```ts
import { FormikFormProps } from "formik";

declare module "formik" {
  export function Form(props: FormikFormProps);
}
```

**Comment by meredithlind** [comment]
Typescript 3.5.3 is released and fixes this issue  🎉 

See [microsoft/TypeScript#31676](https://github.com/microsoft/TypeScript/issues/31676#issuecomment-509493786)

**Comment by jaredpalmer** [comment]
Going to deprecate that release and rebuild with 3.5.3
