### ISSUE TITLE
Type error on Form element in 2.1.1

### ISSUE THREAD

**Issue by pixelbreaker** [jaredpalmer/formik#2168]
### Current Behavior

Typescript throws a type error when I update from 2.0.6 to 2.1.1 on the `Form` component.

```
error TS2741: Property 'translate' is missing in type '{ children: Element[]; className: string; }' but required in type 'Pick<DetailedHTMLProps<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>, "target" | "name" | ... 260 more ... | "translate">'.

53               <Form className={styles.form}>
```

### Expected behavior

There shouldn't be an error

### Reproducible example

I couldn't reproduce without typescript, but if I add the prop `translate=""` to `Form` it stops the error.

### Suggested solution(s)

Update the typings in Form.d.ts?

### Additional context

If I add the prop `translate=""` to `Form` it stops the error. If I roll back to 2.0.6 it works fine.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.1
| React            | 16.12.0
| TypeScript       | 3.7.4
| Browser          | Not applicable here
| npm/Yarn         | Yarn
| Operating System | MacOS Catalina

**Comment by arman94** [comment]
i have the same issue

**Comment by jaredpalmer** [comment]
Good catch, can someone make a PR?

**Comment by pixelbreaker** [comment]
@jaredpalmer I would but I'm not exactly sure what the fix is. Is it to do with the react type defs or do we need to exclude `translate` from the `Form` type defs?

**Comment by omkar-joshi** [comment]
I'd like to help with this

**Comment by jaredpalmer** [comment]
Duplicate of #2120
